[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["./node_modules/.bin/prisma generate", "npm run build"]

[start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
